name: Deploy react-app 

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: self-hosted  
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check working directory
        run: pwd
      
      - name: List files in current directory
        run: ls -al

      # Add working directory for npm commands
      - name: Build and Deploy
        working-directory: /home/ubuntu/React-GA/actions-runner/_work/React-GA/React-GA/react-cicd
        run: |
          npm install
          npm run build
          
          sudo cp -r ./build/* /var/www/html

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
